services:
  apache:
    build: ./apache
    image: pg23022-imagen
    container_name: pg23022-contenedor
    restart: always
    volumes:
      - ./ejercicios:/var/www/html
    ports:
      - "8089:80"
    